### ISSUE TITLE
Build wheels for python 3.10

### ISSUE THREAD

**Issue by emanuele-f** [chaquo/build-wheel#15]
Hi, I'm trying to compile the new cryptography 38 module for Python 3.10, needed by mitmproxy 9.

I can see that the build scripts in this project still require python 3.8. In https://github.com/chaquo/chaquopy/blob/13.0.0/server/pypi/build-wheel.py I can see a new `--python` parameter to specify the python version, which is missing in build-wheel. How can I build wheels for python 3.10?

**Comment by mhsmith** [comment]
To build for Python versions other than 3.8, you'll need to use the copy of the tool in the `chaquopy` repository. I'll write up some instructions on how to use it, and then post another comment here.

**Comment by mhsmith** [comment]
Instructions for using the new version of build-wheel can now be found [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi). The old build-wheel repository will be archived shortly.
